#!/usr/bin/env zsh

# Keep app-specific aliases in home/config/<app>/rc.zsh files.

# +---------+
# | testing |
# +---------+

alias oprber="op run -- bundle exec ruby"

# +----------+
# | dotfiles |
# +----------+

alias df="cd $HOME/Developer/dotfiles/files/config; cl"

alias zshenv="$VISUAL $ZDOTDIR/zshenv"
alias zprofile="$VISUAL $ZDOTDIR/zprofile"
alias zshrc="$VISUAL $ZDOTDIR/zshrc"
alias zlogin="$VISUAL $ZDOTDIR/zlogin"
alias zlogout="$VISUAL $ZDOTDIR/zlogout"

alias al="$VISUAL $ZDOTDIR/source/aliases"

# +-----------------+
# | file management |
# +-----------------+

alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -i'

# +----+
# | ls |
# +----+

alias ls='eza --group-directories-first'
alias la='eza -a --group-directories-first'
alias lsl='eza -l --header --group-directories-first --git --time-style=long-iso --icons=auto'
alias lal='eza -la --header --group-directories-first --git --time-style=long-iso --icons=auto'

# +------------------+
# | System Clipboard |
# +------------------+

alias copy='pbcopy <'
alias pst='pbpaste >'

# +-----+
# | Zsh |
# +-----+

alias cl='clear'
alias d='dirs -v'                                               # view directory stack
for index ({1..9}) alias "$index"="cd +${index}"; unset index   # access directory stack
alias hst='history'

# +-----------------------+
# | other w/o config dirs |
# +-----------------------+

alias psl="cd $HOME/Developer/pause-loop; cl"
alias ss="cd $HOME/Developer/slowsort; cl"
alias dt="cd $HOME/Developer/devtools; cl"
