#:schema https://developers.openai.com/codex/config-schema.json

model = "gpt-5.5"
model_reasoning_effort = "high"
plan_mode_reasoning_effort = "xhigh"
model_reasoning_summary = "detailed"
model_verbosity = "high"
personality = "pragmatic"

sandbox_mode = "workspace-write"
allow_login_shell = false


notify = ["/Users/eric/Developer/dotfiles/files/config/codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended"]

[sandbox_workspace_write]
network_access = true

[agents]
max_threads = 10

[mcp_servers.github_ericdobson]
url = "https://api.githubcopilot.com/mcp/"
bearer_token_env_var = "CODEX_GITHUB_MCP_ERICDOBSON"
default_tools_approval_mode = "approve"

[projects."/Users/eric/Developer/dotfiles"]
trust_level = "trusted"

[projects."/Users/eric/Developer/notes"]
trust_level = "trusted"

[projects."/Users/eric/Developer/pause-loop"]
trust_level = "trusted"

[projects."/Users/eric/Developer/devtools"]
trust_level = "trusted"

[projects."/Users/eric/Developer/slowsort"]
trust_level = "trusted"

[projects."/Users/eric/Developer/ericdobson.com"]
trust_level = "trusted"

[projects."/Users/eric/Developer/creating-flow"]
trust_level = "trusted"

[projects."/Users/eric/Developer/creating-flow-corpus-project"]
trust_level = "trusted"

[marketplaces.openai-bundled]
last_updated = "2026-05-18T17:05:11Z"
source_type = "local"
source = "/Users/eric/.config/codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-06-01T18:13:38Z"
source_type = "local"
source = "/Users/eric/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[desktop]
followUpQueueMode = "steer"
git-commit-instructions = "Commit messages should succinctly describe the total effect of changes made, not just the most recent edits. For example if a new feature is added, then a couple small edits are staged, the commit message should reflect the feature, not the small edits."
git-pr-instructions = ""
conversationDetailMode = "STEPS_COMMANDS"
