[Fastmail]
source            = jmap+oauthbearer://@api.fastmail.com/jmap/session
source-cred-cmd   = op read "op://Eric/dhjivpxsxyh2vtt5vdxi75elvy/credential"
default           = Inbox
from              = Eric Dobson <email@ericdobson.com>
copy-to           = Sent
