[[profiles]]
id = '69B5E12B-B5D2-4502-A664-D1195C039B5C'
name = 'Default'

[[profiles.workspaces]]
display = 'LU28R55'
id = 'B4EAA89B-13D4-4A0B-A258-10D23A13DF13'
name = 'Browsing'
openAppsOnActivation = false
shortcut = 'cmd+shift+1'
symbolIconName = 'globe'

[profiles.workspaces.appToFocus]
bundleIdentifier = 'com.kagi.kagimacOS'
iconPath = '/Applications/Orion.app/Contents/Resources/AppIcon.icns'
name = 'Orion'

[[profiles.workspaces.apps]]
bundleIdentifier = 'com.kagi.kagimacOS'
iconPath = '/Applications/Orion.app/Contents/Resources/AppIcon.icns'
name = 'Orion'

[[profiles.workspaces]]
display = 'LU28R55'
id = '9CB6AFD0-7DBC-4589-92E9-91FBA1587815'
name = 'Coding'
openAppsOnActivation = false
shortcut = 'cmd+shift+2'
symbolIconName = 'apple.terminal'

[profiles.workspaces.appToFocus]
bundleIdentifier = 'net.kovidgoyal.kitty'
iconPath = '/Applications/kitty.app/Contents/Resources/kitty.icns'
name = 'kitty'

[[profiles.workspaces.apps]]
bundleIdentifier = 'net.kovidgoyal.kitty'
iconPath = '/Applications/kitty.app/Contents/Resources/kitty.icns'
name = 'kitty'