# CURSOR
#
# https://sw.kovidgoyal.net/kitty/conf/#text-cursor-customization

cursor                     none
cursor_beam_thickness      1.5
cursor_underline_thickness 2.0
cursor_blink_interval      0.0
cursor_stop_blinking_after 0.15
