# ENVIRONMENT
#
# https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.env

# establish xdg-compliant directories
env XDG_CONFIG_HOME=${HOME}/.config
env XDG_CACHE_HOME=${HOME}/.cache
env XDG_DATA_HOME=${HOME}/.local/share
env XDG_STATE_HOME=${HOME}/.local/state
env XDG_BIN_HOME=${HOME}/.local/bin

# set path from scratch
env PATH=${XDG_BIN_HOME}:
    \/opt/homebrew/bin:
    \/opt/homebrew/sbin:
    \/usr/local/bin:
    \/usr/bin:
    \/bin:
    \/usr/sbin:
    \/sbin

# zsh
env ZDOTDIR=${XDG_CONFIG_HOME}/zsh

# editors
env VISUAL=hx
env EDITOR=${VISUAL}

# app-specific environment variables and path setup
globinclude ../**/env.conf

# gnupg doesn't work with globinclude due to symlink
include ../gnupg/env.conf
