# FONTS
#
# https://sw.kovidgoyal.net/kitty/conf/#fonts

font_family       JetBrainsMono Nerd Font Mono ExtraLight
bold_font         JetBrainsMono Nerd Font Mono Medium
italic_font       JetBrainsMono Nerd Font Mono ExtraLight Italic
bold_italic_font  JetBrainsMono Nerd Font Mono Medium Italic

font_size         15.5
disable_ligatures always
font_features     none
