# KEYBOARD SHORTCUTS
#
# https://sw.kovidgoyal.net/kitty/conf/#keyboard-shortcuts

# SCROLLING

map --allow-fallback=shifted,ascii shift+cmd+h show_scrollback

# WINDOW NAVIGATION

map alt+n new_window
map ctrl+shift+enter

map alt+shift+n new_window_with_cwd

map alt+w close_window_with_confirmation ignore-shell

map alt+shift+w close_other_windows_in_tab

map alt+shift+] next_window
map ctrl+shift+]
map alt+shift+[ previous_window
map ctrl+shift+[

# WINDOW LAYOUT

map alt+shift+h goto_layout tall
map alt+shift+v goto_layout fat
map alt+shift+f toggle_layout stack
map alt+shift+m move_window_to_top

map alt+left neighboring_window left
map alt+right neighboring_window right
map alt+up neighboring_window top
map alt+down neighboring_window bottom

map alt+shift+left move_window left
map alt+shift+right move_window right
map alt+shift+up move_window top
map alt+shift+down move_window bottom
