# KEYBOARD SHORTCUTS
#
# https://sw.kovidgoyal.net/kitty/conf/#keyboard-shortcuts

# scrolling
map --allow-fallback=shifted,ascii shift+cmd+h show_scrollback

# window navigation
map alt+shift+] next_window
map alt+shift+[ previous_window
map ctrl+shift+]
map ctrl+shift+[
