# kitty.conf
#
# https://sw.kovidgoyal.net/kitty/conf/

shell /opt/homebrew/bin/nu

include environment.conf

include fonts.conf
include cursor.conf
include scrollback.conf
include mouse.conf
include performance_tuning.conf
include terminal_bell.conf
include window_layout.conf
include tab_bar.conf
include advanced.conf
include macos.conf
include keyboard_shortcuts.conf

# Tinted Terminal
include /Users/eric/.local/share/tinted-theming/tinty/tinted-terminal-themes-kitty-file.conf

# Theme-independent appearance overrides.
include theme_overrides.conf
