# kitty.conf
#
# https://sw.kovidgoyal.net/kitty/conf/

shell .

include fonts.conf
include cursor.conf
include scrollback.conf
include mouse.conf
include performance_tuning.conf
include terminal_bell.conf
include window_layout.conf
include tab_bar.conf
include advanced.conf
include macos.conf
include keyboard_shortcuts.conf


# BEGIN_KITTY_THEME
# Monokai Soda
include current-theme.conf
# END_KITTY_THEME

# Theme-independent appearance overrides.
include theme_overrides.conf
