# macOS SPECIFIC TWEAKS
#
# https://sw.kovidgoyal.net/kitty/conf/#os-specific-tweaks

macos_quit_when_last_window_closed yes
macos_thicken_font 0.5
macos_traditional_fullscreen no
macos_show_window_title_in none
macos_option_as_alt yes
