# WINDOW LAYOUT
#
# https://sw.kovidgoyal.net/kitty/conf/#window-layout

remember_window_size     no
initial_window_width     120c
initial_window_height    38c

window_margin_width 2
window_padding_width 5

inactive_text_alpha 0.3

hide_window_decorations titlebar-only

enabled_layouts fat, tall, stack
