"$schema" = 'https://starship.rs/config-schema.json'

format = """
[╭─](dimmed white) \
[$username@$hostname](green)\
[ in ](dimmed white)\
${custom.path_parents}\
${custom.path_leaf} \
$git_branch\
$git_status
[╰─](dimmed white)$character"""

right_format = "$cmd_duration${custom.github}"

add_newline = false

[username]
show_always = true
format = "$user"

[hostname]
ssh_only = false
format = "$hostname"

[custom.path_parents]
shell = ["zsh", "--no-rcs"]
when = "true"
command = """
path="${PWD/#$HOME/~}"

if [[ "$path" == "/" || "$path" == "~" ]]; then
  print -r -- ""
else
  parent="${path:h}"

  if [[ "$parent" == "." ]]; then
    print -r -- ""
  elif [[ "$parent" == "/" ]]; then
    print -r -- "/"
  else
    print -r -- "$parent/"
  fi
fi
"""
format = "[$output](dimmed blue)"

[custom.path_leaf]
shell = ["zsh", "--no-rcs"]
when = "true"
command = """
path="${PWD/#$HOME/~}"

if [[ "$path" == "/" || "$path" == "~" ]]; then
  print -r -- "$path"
else
  print -r -- "${path:t}"
fi
"""
format = "[$output](blue)"

[custom.github]
command = "git config --get remote.origin.url | sed -E 's#(git@github.com:|https://github.com/)##; s#\\.git$##'"
when = "git rev-parse --is-inside-work-tree >/dev/null 2>&1"
format = "[$output](dimmed purple)"

[cmd_duration]
min_time = 0
format = "[took $duration]($style) "
style = "dimmed white"

[git_branch]
style = 'purple'

[git_status]
format = "[$conflicted$deleted$modified$renamed$typechanged$staged$untracked$ahead_behind$stashed]($style)"

conflicted = "[=${count} ](bold red)"
deleted    = "[✘${count} ](red)"
modified   = "[!${count} ](yellow)"
renamed    = "[»${count} ](yellow)"
typechanged= "[T${count} ](yellow)"
staged     = "[+${count} ](green)"
untracked  = "[?${count} ](purple)"

ahead      = "[⇡${count} ](blue)"
behind     = "[⇣${count} ](blue)"
diverged   = "[⇕⇡${ahead_count}⇣${behind_count} ](yellow)"

stashed    = "[*${count} ](dimmed purple)"
